#! /usr/bin/python
'''
 *  $Id: JobOpt_Rec0_SubPed, 2015-04-25 10:56:31 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
#-------------------------------------------------------------------
    NOTE:   input data is scientific root data(after Hex2Root)
'''

#-------------------------------------------------------------------
import os
import sys
import DMPSW                    # Load DAMPE software
import libDmpRec0 as DmpRec0

#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.SetEventNumber(2000)     # default: -1
#DMPSW.Core.SetStartTime("2014-11-18 20:30:10")     # default: 2013-01-01 00:00:00
#DMPSW.Core.SetStopTime("2014-11-18 20:40:30")      # default: 2053-01-01 00:00:00
#DMPSW.Core.LogLevel("Debug")      # Value = {Error | Warning | Info | Debug}. default: Info.
#DMPSW.Core.LogHeader("On") # default: off

#-------------------------------------------------------------------
# RootIOSvc options
#DMPSW.RootIOSvc.InputPath(os.environ["DMPSWWORK"]+"/data/sci")
inputFileName = "./A2Data00_20141118_214521-Rdc.root"
if len(sys.argv) == 2:
        inputFileName = sys.argv[1]
print inputFileName
exit
DMPSW.RootIOSvc.SetInputFile(inputFileName)
#DMPSW.RootIOSvc.SetOutputFile("./Dmptest15.root")
DMPSW.RootIOSvc.SetWriteList("Event/Rec0")  # split by ;
#DMPSW.RootIOSvc.OutputPath(os.environ["DMPSWWORK"]+"/run/data/cal/ped")

#-------------------------------------------------------------------
# Creat user's service or algorithm
Rec0 = DmpRec0.DmpAlgRec0_SubPed()
DMPSW.AlgMgr.Append(Rec0)
Quality = DmpRec0.DmpAlgRec0_DataQuality()
DMPSW.AlgMgr.Append(Quality)

def findPedFile(path,ID,ref_time):
        ped_time="0"
        ped_fn="NO"
        fNamoes=os.listdir(path)
        for fn in fNamoes:
                if (".ped" not in fn) or (ID not in fn):
                        continue
                fn_time = fn[13:21]
                fn_time = fn_time+fn[22:28]
                if (int(fn_time) <= int(ref_time) and int(fn_time) > int(ped_time)):
                        ped_time = fn_time
                        ped_fn = fn
        return ped_fn

inputStem = inputFileName.split("/")
inputStem = inputStem[-1]
inf_time = inputStem[9:17]
inf_time = inf_time+inputStem[18:24]
pedPath ="/home/chi/dmpwork/MyData/Calibration/DAMPE/Pedestal/"
for iD in ["Bgo","Psd","Stk","Nud"]:
        pedf = findPedFile(pedPath,iD,inf_time)
        Rec0.SetPedestalFile(iD,pedPath+pedf)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

